name: Publish docs

on:
  push:
    branches: [develop, main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    uses: wphillipmoore/standard-actions/.github/workflows/publish-docs.yml@v1.5
    with:
      pre-deploy-command: >-
        git clone --depth 1 --branch develop
        https://github.com/wphillipmoore/mq-rest-admin-common.git
        .mq-rest-admin-common
